// import iconSet from 'quasar/icon-set/fontawesome-v5.js'
// import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'
import iconSet from 'quasar/icon-set/material-icons'
import '@quasar/extras/material-icons/material-icons.css'
// import '@quasar/extras/roboto-font/roboto-font.css'
import '../../assets/styles/quasar.styl'
import 'quasar/dist/quasar.ie.polyfills'
import {
  ClosePopup,
  date,
  Dialog,
  Notify,
  TouchSwipe,
  QAvatar,
  QBadge,
  QBanner,
  QBar,
  QBtn,
  QBtnGroup,
  QCard,
  QCardActions,
  QCardSection,
  QChip,
  QDate,
  QDialog,
  QDrawer,
  QFile,
  QFooter,
  QForm,
  QHeader,
  QIcon,
  QImg,
  QInput,
  QItem,
  QItemLabel,
  QItemSection,
  QKnob,
  QLayout,
  QLinearProgress,
  QList,
  QMarkupTable,
  QMenu,
  QPage,
  QPageContainer,
  QPopupProxy,
  QRating,
  QScrollArea,
  QSelect,
  QSeparator,
  QSlider,
  QSpace,
  QSpinnerDots,
  QTable,
  QTd,
  QToolbar,
  QToolbarTitle,
  QTooltip
} from 'quasar'

export default {
  config: {},
  components: {
    QAvatar,
    QBadge,
    QBanner,
    QBar,
    QBtn,
    QBtnGroup,
    QCard,
    QCardActions,
    QCardSection,
    QChip,
    QDate,
    QDialog,
    QDrawer,
    QFile,
    QFooter,
    QForm,
    QHeader,
    QIcon,
    QImg,
    QInput,
    QItem,
    QItemLabel,
    QItemSection,
    QKnob,
    QLayout,
    QLinearProgress,
    QList,
    QMarkupTable,
    QMenu,
    QPage,
    QPageContainer,
    QPopupProxy,
    QRating,
    QScrollArea,
    QSelect,
    QSeparator,
    QSlider,
    QSpace,
    QSpinnerDots,
    QTable,
    QTd,
    QToolbar,
    QToolbarTitle,
    QTooltip
  },
  directives: {
    ClosePopup,
    TouchSwipe
  },
  iconSet: iconSet,
  utils: {
    date
  },
  plugins: {
    Dialog,
    Notify
  },
}
